### ISSUE TITLE
TypeError: arguments.includes is not a function

### ISSUE THREAD

**Issue by aboutte** [perforce/setup-p4#51]
After merging in #50 integration tests started failing with the following error:

```
(node:1684) UnhandledPromiseRejectionWarning: TypeError: arguments.includes is not a function
    at main (/home/runner/work/setup-p4-example-build-template/setup-p4-example-build-template/.github/actions/setup-p4/dist/index.js:13710:19)
    at setupP4 (/home/runner/work/setup-p4-example-build-template/setup-p4-example-build-template/.github/actions/setup-p4/dist/index.js:13646:3)
    at /home/runner/work/setup-p4-example-build-template/setup-p4-example-build-template/.github/actions/setup-p4/dist/index.js:13793:1
    at /home/runner/work/setup-p4-example-build-template/setup-p4-example-build-template/.github/actions/setup-p4/dist/index.js:13795:3
    at Object.<anonymous> (/home/runner/work/setup-p4-example-build-template/setup-p4-example-build-template/.github/actions/setup-p4/dist/index.js:13798:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:10[27](https://github.com/perforce/setup-p4-example-build-template/runs/5500668658?check_suite_focus=true#step:6:27):10)
    at Module.load (internal/modules/cjs/loader.js:863:[32](https://github.com/perforce/setup-p4-example-build-template/runs/5500668658?check_suite_focus=true#step:6:32))
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
(node:1684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is an [example](https://github.com/perforce/setup-p4/runs/5498709495?check_suite_focus=true).
